language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - hhvm

services:
  - mysql

test:
  adapter: mysql2
  database: simple_auth_test
  username: travis
  encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE simple_auth_test;'
  - mysql -u root simple_auth_test < sql/tables.sql

script: phpunit tests/Test.php
